version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: cimg/node:17.2.0

    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Test Reporter
          command: |
            wget -O ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter
      - run:
          name: Report Before Build
          command: ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: npm run test
      
workflows:
  sample:
    jobs:
      - build-and-test

notification:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${{secrets.COVERALLS_REPO_TOKEN}}
    